import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/global/theme-provider'
import Header from '@/components/store/header/Header'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className='container'>  <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          ><div className="sticky  top-0 bg-black z-50 w-full">
          <Header />
      </div>
            {children} </ThemeProvider></body>
    </html>
  )
}
